# docker-compose.patent.yml
services:
  bas-gate:
    build:
      context: ./apps/services/bas-gate
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8101
    environment:
      - PGHOST=host.docker.internal
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
    ports: ["8101:8101"]

  recon:
    build:
      context: ./apps/services/recon
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8102
    environment:
      - PGHOST=host.docker.internal
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
    ports: ["8102:8102"]

  bank-egress:
    build:
      context: ./apps/services/bank-egress
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8103
    environment:
      - PGHOST=host.docker.internal
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - APGMS_RPT_SECRET=dev-secret-change-me
    ports: ["8103:8103"]

  audit:
    build:
      context: ./apps/services/audit
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8104
    environment:
      - PGHOST=host.docker.internal
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
    ports: ["8104:8104"]
