name: Bug
description: Document a defect impacting expected behavior.
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the observed problem and affected experience.
      placeholder: Provide a brief overview of the bug.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps that consistently reproduce the issue.
      placeholder: |
        1. Step one
        2. Step two
        3. Observe failure
    validations:
      required: true
  - type: input
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Explain what should happen instead.
      placeholder: The system should...
    validations:
      required: true
  - type: input
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Describe what is happening currently.
      placeholder: The system actually...
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: List the conditions that confirm the bug has been resolved.
      placeholder: |
        - [ ] Scenario 1 fixed
        - [ ] Scenario 2 verified
    validations:
      required: true
  - type: textarea
    id: test_plan
    attributes:
      label: Test Plan
      description: Detail regression, automation, or monitoring needed to validate the fix.
      placeholder: Include unit, integration, and manual checks.
    validations:
      required: true
  - type: textarea
    id: rollback_notes
    attributes:
      label: Rollback Notes
      description: Describe how to revert the change if it introduces regressions.
      placeholder: Link to prior version, toggles, or recovery steps.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment & Logs
      description: Capture environment details, logs, or screenshots relevant to the bug.
    validations:
      required: false
