services:
  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.retention.time=2d"]
    ports:
      - "9090:9090"
    volumes:
      - "./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    depends_on:
      - normalizer
      - tax-engine
      - nats-exporter

  # Exporter that scrapes NATS server monitoring endpoints and exposes Prom metrics
  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command:
      - "-varz=http://nats:8222"
      - "-connz=http://nats:8222"
      - "-routez=http://nats:8222"
      - "-serverz=http://nats:8222"
      - "-subz=http://nats:8222"
      - "-gatewayz=http://nats:8222"
      - "-jsz=http://nats:8222"
    ports:
      - "7777:7777"
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1:7777/metrics >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    depends_on:
      nats:
        condition: service_healthy

  # Extend grafana service from base compose with provisioning mounts
  grafana:
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - "./ops/grafana/provisioning/alerting:/etc/grafana/provisioning/alerting:ro"
      - "./ops/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro"
      - "./ops/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro"
      - "./ops/grafana/dashboards:/var/lib/grafana/dashboards:ro"


