/* eslint-disable */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/balance": {
    get: {
      parameters: {
        query: components["parameters"]["BalanceQuery"];
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["BalanceResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/ledger": {
    get: {
      parameters: {
        query: components["parameters"]["BalanceQuery"];
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["LedgerResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    BalanceResponse: {
      abn: string;
      taxType: string;
      periodId: string;
      balance_cents: number;
      has_release: boolean;
    };
    LedgerRow: {
      id: number;
      amount_cents: number;
      balance_after_cents: number;
      rpt_verified: boolean;
      release_uuid: string | null;
      bank_receipt_id: string | null;
      created_at: string;
    };
    LedgerResponse: {
      abn: string;
      taxType: string;
      periodId: string;
      rows: components["schemas"]["LedgerRow"][];
    };
    ErrorResponse: {
      error: string;
      detail?: string;
    };
  };
  parameters: {
    BalanceQuery: {
      abn: string;
      taxType: string;
      periodId: string;
    };
  };
}

export interface operations {}

export interface external {}
