FROM python:3.11-slim

WORKDIR /app

# Copy source
COPY app ./app
COPY libs/json /libs/schemas/json

# Minimal runtime deps only
RUN pip install --no-cache-dir \
    fastapi \
    "uvicorn[standard]" \
    pydantic \
    nats-py \
    orjson \
    prometheus-client

EXPOSE 8001
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8001"]
