name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  golden:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run BAS golden vectors
        shell: pwsh
        run: ./tools/run_golden.ps1 --all
