name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/apgms
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: apgms
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: apgms
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install -r portal-api/requirements.txt

      - name: Run database migrations
        run: npm run migrate

      - name: Generate OpenAPI spec
        run: npm run openapi

      - name: Generate SDK types
        run: npm run client:gen

      - name: Ensure generated artifacts are committed
        run: git diff --exit-code

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Seed database
        run: npm run seed

      - name: Smoke check
        run: npm run smoke
