name: Readiness Scorecard

on:
  push:
    branches:
      - main
      - work
  pull_request:

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run readiness:score
      - name: Upload readiness report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: readiness-report
          path: |
            artifacts/readiness/report.md
            public/badges
          if-no-files-found: warn
