name: Smoke

on:
  push:
    branches: ["main", "master", "develop", "dev", "release/*"]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: apgms
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d apgms" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Seed database
        env:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/apgms
        run: npm run seed

      - name: Smoke test
        env:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/apgms
        run: npm run smoke
